version: '3.8'

services:
    django:
        build: ./sharetech
        volumes:
            - ./sharetech/:/usr/src/sharetech/
        ports:
            - 8000:8000
        environment:
            - DEBUG=1
            - SECRET_KEY=django-insecure-an)d383q66a%4doo4(t1_iut-xcapi87m+rph*na-v@un=d3uu
            - DATABASE_ENGINE=django.db.backends.mysql
            - DATABASE_NAME=sharetech
            - DATABASE_USER=django
            - DATABASE_PASSWORD=django123A!
            - DATABASE_HOST=mysql
            - DATABASE_PORT=3306
        depends_on: 
            - mysql

    mysql:
      # M1チップ対応のためplatform指定
      platform: linux/x86_64
      image: mysql:8.0
      volumes:
        - mysql_data:/var/lib/mysql
        - ./initdb.d:/docker-entrypoint-initdb.d
      environment:
            - MYSQL_ROOT_PASSWORD=root123A!
            - MYSQL_USER=django
            - MYSQL_PASSWORD=django123A!
            - MYSQL_DB=sharetech
      command: bash -c 'usermod -o -u $LINUX_MYSQL_UID mysql; groupmod -o -g $LINUX_MYSQL_GID mysql; chown -R mysql:root /var/run/mysqld/ /var/log/mysql/ /var/lib/mysql/; /entrypoint.sh mysqld --user=mysql --console'
volumes:
  mysql_data: