# Generated by Django 3.2.5 on 2021-08-05 13:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='必須項目です。全角文字、半角英数字、@/./+/-/_で50文字以下にしてください。', max_length=50, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Name')),
                ('role_id', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)], verbose_name='Account Role')),
                ('icon_path', models.CharField(max_length=255, null=True, verbose_name='アイコン画像パス')),
                ('company', models.CharField(max_length=255, null=True, verbose_name='Company')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(30)], verbose_name='password')),
                ('email_verified_at', models.DateTimeField(null=True, verbose_name='メールアドレス確認日')),
                ('remember_token', models.CharField(max_length=512, null=True, verbose_name='トークン')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Create Date')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Update Date')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete Date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
