# Generated by Django 3.2.9 on 2021-11-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id_deleted',
            new_name='is_deleted',
        ),
    ]
