# Generated by Django 3.2.9 on 2021-11-19 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0002_rename_id_deleted_customuser_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, verbose_name='カテゴリ名')),
                ('parent_category_id', models.PositiveIntegerField(null=True, verbose_name='親カテゴリID')),
                ('id_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Update Date')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete Date')),
            ],
            options={
                'db_table': 'category_mst',
            },
        ),
        migrations.CreateModel(
            name='ConsultWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consult_window_title', models.CharField(max_length=128, verbose_name='相談窓口タイトル')),
                ('consult_window_overview', models.CharField(max_length=512, verbose_name='相談窓口概要')),
                ('consult_price', models.PositiveIntegerField(default=0, verbose_name='相談料金')),
                ('timerex_url', models.CharField(max_length=512, verbose_name='timerex URL')),
                ('viewed_num', models.PositiveIntegerField(default=0, verbose_name='閲覧数')),
                ('applyed_num', models.PositiveIntegerField(default=0, verbose_name='申込数')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Update Date')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete Date')),
                ('expert_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='専門家ユーザーID')),
            ],
            options={
                'db_table': 'consult_window',
            },
        ),
        migrations.CreateModel(
            name='CategoryConsultWindowMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Update Date')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete Date')),
                ('category_id', models.ForeignKey(null=True, on_delete=models.SET(1), to='sharetech.categorymst', verbose_name='カテゴリID')),
                ('consult_window_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharetech.consultwindow', verbose_name='相談窓口ID')),
            ],
            options={
                'db_table': 'category_consult_window_mapping',
            },
        ),
    ]
