# Generated by Django 3.2.9 on 2021-11-21 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0004_auto_20211121_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryconsultwindowmapping',
            name='category_id',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='sharetech.categorymst', verbose_name='カテゴリID'),
        ),
    ]
