# Generated by Django 3.2.9 on 2021-11-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0006_categorymst_category_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymst',
            name='parent_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharetech.categorymst', verbose_name='親カテゴリID'),
        ),
    ]
