# Generated by Django 3.2.9 on 2021-12-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0008_auto_20211129_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tmp_email',
            field=models.EmailField(max_length=256, null=True, verbose_name='Tmp Email'),
        ),
    ]
