# Generated by Django 3.2.9 on 2021-12-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0010_auto_20211209_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupationmst',
            old_name='oname',
            new_name='name',
        ),
    ]
