# Generated by Django 3.2.9 on 2021-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0011_rename_oname_occupationmst_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role_code',
            field=models.CharField(choices=[('1', '専門家'), ('2', '一般')], default=1, max_length=1, verbose_name='Account Role'),
        ),
    ]
