# Generated by Django 3.2.9 on 2021-12-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0012_alter_customuser_role_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon_path',
            field=models.ImageField(null=True, upload_to='img', verbose_name='Icon Image Path'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role_code',
            field=models.CharField(choices=[('1', '専門家'), ('2', '一般')], default=2, max_length=1, verbose_name='Account Role'),
        ),
    ]
