# Generated by Django 3.2.9 on 2021-12-16 11:52

from django.db import migrations, models
import sharetech.utils.set_image_name


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0013_auto_20211210_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon_path',
            field=models.ImageField(null=True, upload_to=sharetech.utils.set_image_name.SetImageName.set_icon_name, verbose_name='Icon Image Path'),
        ),
    ]
