# Generated by Django 3.2.9 on 2021-12-15 12:11

from django.db import migrations, models
import sharetech.utils.set_image_name


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0013_auto_20211210_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username_kana',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='family_name_en',
            field=models.CharField(help_text='必須項目です。全角文字で20文字以下にしてください。', max_length=20, verbose_name='Family Name Englist'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='family_name_jp',
            field=models.CharField(help_text='必須項目です。全角文字で20文字以下にしてください。', max_length=20, verbose_name='Family Name Japanese'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name_en',
            field=models.CharField(help_text='必須項目です。全角文字で20文字以下にしてください。', max_length=20, verbose_name='First Name Englist'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name_jp',
            field=models.CharField(help_text='必須項目です。全角文字で20文字以下にしてください。', max_length=20, verbose_name='First Name Japanese'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='icon_path',
            field=models.ImageField(null=True, upload_to=sharetech.utils.set_image_name.SetImageName.set_icon_name, verbose_name='Icon Image Path'),
        ),
    ]
