# Generated by Django 3.2.9 on 2021-12-18 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0014_auto_20211215_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpecialize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialize', models.CharField(max_length=32, verbose_name='専門分野')),
                ('id_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Update Date')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete Date')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='申込者ID')),
            ],
            options={
                'db_table': 'user_specialize',
            },
        ),
    ]
