# Generated by Django 3.2.9 on 2021-12-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0015_userspecialize'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userspecialize',
            constraint=models.UniqueConstraint(fields=('user_id', 'specialize'), name='specialize_unique'),
        ),
    ]
