# Generated by Django 3.2.9 on 2021-12-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0016_userspecialize_specialize_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userspecialize',
            old_name='id_deleted',
            new_name='is_deleted',
        ),
    ]
