# Generated by Django 3.2.9 on 2021-12-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0017_rename_id_deleted_userspecialize_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='archivement',
            field=models.CharField(max_length=512, null=True, verbose_name='Archivement'),
        ),
    ]
