# Generated by Django 4.0 on 2021-12-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0014_alter_customuser_icon_path'),
        ('sharetech', '0018_customuser_archivement'),
    ]

    operations = [
    ]
