# Generated by Django 4.0 on 2021-12-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0019_merge_20211225_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryconsultwindowmapping',
            old_name='id_deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='categorymst',
            old_name='id_deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='consultapply',
            old_name='id_deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='industrymst',
            old_name='id_deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='occupationmst',
            old_name='id_deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='positionmst',
            old_name='id_deleted',
            new_name='is_deleted',
        ),
    ]
