# Generated by Django 4.0 on 2021-12-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0019_merge_20211221_0351'),
        ('sharetech', '0020_rename_id_deleted_categoryconsultwindowmapping_is_deleted_and_more'),
    ]

    operations = [
    ]
