# Generated by Django 4.0 on 2022-01-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0021_merge_20211227_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultwindow', # モデル名
            old_name='timerex_url',   # 変更前
            new_name='scheduler_url'    # 変更後
        )
    ]
