# Generated by Django 4.0 on 2022-01-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0021_merge_20211227_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Activated'),
        ),
    ]
