# Generated by Django 4.0 on 2022-01-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0022_alter_customuser_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Activated'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
    ]
