# Generated by Django 4.0 on 2022-01-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharetech', '0024_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
    ]
